### ISSUE TITLE
Dashboard for projects

### ISSUE THREAD

**Issue by shungo0222** [Succery-dev/escrow#24]
## About feature 
<img width="777" alt="Screen Shot 2023-04-24 at 13 30 02" src="https://user-images.githubusercontent.com/54393289/233902047-e3ea5fdc-dbe4-4dd6-b407-2a59c5203709.png">

![page-flow](https://user-images.githubusercontent.com/54393289/235355764-feb90ec2-7904-4ff5-b954-0077ebe910f7.jpg)

The first pic is the wireframe of the dashboard page. The second pic is page flow.

What I want you to do:

- [x] @Kunal-Khatri-1 Based on the wireframe above, make a design in Figma according to HP (white-base, stylish, simple).  (~5/1)
- [x] @shungo0222  & @Badhan978  review it. (~5/2)
- [x] @Kunal-Khatri-1 Write code according to the design in Figma and make an onboarding page. (~5/3)
- [x] @Kunal-Khatri-1 Refactor the code
- [x] @Kunal-Khatri-1 Apply dark theme
- [x] @shungo0222 check the code

FYI:

- You don't need to implement the button function.
- You don't need to make a connection between this page and the others.
- Each item in the list is a project (Contract between client and lancer and managed by the escrow smart contract.)
- Arrange each project in a list format from top to bottom.

[Figma](https://www.figma.com/file/FcDB77my8Dxb1gRakac7Ac/QubePay-Wireframe?node-id=27-3&t=WsNrT0gm43Zk8Jy5-0)

## Linked issues
#xx

**Comment by shungo0222** [comment]
Changed design to this new one below.

> It is giving more space to line chart and table. This makes line chart more visible/readable and table is less congested on smaller devices.



![Image](https://user-images.githubusercontent.com/54393289/236096787-69ffd465-29e6-4abc-b27e-bf4e3900d8ac.png)

**Comment by Kunal-Khatri-1** [comment]
1. Pushed the code to feature/dashboard
2. Currently dashboard runs on mock data. Later when server is ready, will have to add fetch query and display data as per server.

**Comment by shungo0222** [comment]
What I want you to fix:

- [ ] Remove "Product", "Walkthrough" & "Features" from the navbar

<img width="1680" alt="Screen Shot 2023-05-12 at 18 38 17" src="https://github.com/Succery-dev/escrow/assets/54393289/10b3b112-c00e-4265-8f57-cd6f204d8489">

- [ ] Add space under the navbar

<img width="1680" alt="Screen Shot 2023-05-12 at 18 40 36" src="https://github.com/Succery-dev/escrow/assets/54393289/1ac9c226-7988-4a31-bcea-18b19fba77ff">

- [ ] Add "connect wallet" button

<img width="1680" alt="Screen Shot 2023-05-12 at 18 42 05" src="https://github.com/Succery-dev/escrow/assets/54393289/dd3dd2dd-6900-40f3-892f-4ae06be1cbef">

**Comment by shungo0222** [comment]
https://github.com/Succery-dev/escrow/assets/54393289/e0a24384-fcea-44fc-999b-7de37498ec1d

https://github.com/Succery-dev/escrow/assets/54393289/18ba32af-38d6-4959-9b7b-4f95a24b32c1
