### ISSUE TITLE
Setup domain

### ISSUE THREAD

**Issue by shungo0222** [Succery-dev/escrow#41]
## About feature 
Domain: qubepay.xyz

- [x] First of all, can I buy it?
- [x] Finish the process about nameservers?
- [x] Apply the domain to the project?

-> https://vercel.com/dashboard/succery/domains

## Linked issues
#xx

**Comment by shungo0222** [comment]
It took 23min for the process of nameservers to finish.
