### ISSUE TITLE
Fix HP frontend with Kunal's design

### ISSUE THREAD

**Issue by shungo0222** [Succery-dev/escrow#48]
## About the feature 
**DEADLINE: ~5/7**
This deadline may be a little tight but we need this by at the latest 5/9. So just in case I wanna get it done by 5/7 and spend two days (5/8~9) checking and fixing it.
So, if you're still having trouble with the dashboard page, you can stop it and spend all the time on this.

Branch: `feature/hp-design`

I want you to write code for HP according to the new design you made.
New Design: [Figma](https://www.figma.com/file/qgxgUFwHMAsBaWrVAwf8rj/Redesigned-HP?node-id=0-1)
Here are a few things I want you to fix.

**[Navbar]**
- You can hide the "Wallet Connect" button

**[IntroSection]**
<img width="566" alt="Screen Shot 2023-05-05 at 21 00 31" src="https://user-images.githubusercontent.com/54393289/236452372-3c71aa7e-cb3a-4fa1-8162-2886491fb1af.png">

- "Explore" button -> "Join Waitlist" button like [this](https://www.qubepay.xyz/)

**[User-friendly and Secure]**
<img width="869" alt="Screen Shot 2023-05-05 at 21 03 31" src="https://user-images.githubusercontent.com/54393289/236453073-cf2dce75-c9c5-4704-b42f-f2c492c4e68c.png">

- (Typo) Clients easily create custom smart contracts with the lancer’s wallet address.

**[Footer]**
<img width="910" alt="Screen Shot 2023-05-05 at 20 54 37" src="https://user-images.githubusercontent.com/54393289/236453612-7ba73d23-76ef-4a71-9023-acad9ca0bb7c.png">
<img width="1577" alt="Screen Shot 2023-05-05 at 20 54 52" src="https://user-images.githubusercontent.com/54393289/236453621-1fa25556-4725-485f-8154-4127779eb8b1.png">

- Like the current [HP's footer](https://www.qubepay.xyz/), we only need "Twitter", "Privacy Policy", "Terms & Conditions" and "© 2023 QubePay org" buttons.

**[Things needed to be added]**

- Use cases such as Payment on Outsourcing to freelancers, Payment while doing NFT marketing with influencers, Payment to DAO contributors, Paying salaries to employees… etc (Like below)
<img width="1370" alt="Screen Shot 2023-05-05 at 21 10 07" src="https://user-images.githubusercontent.com/54393289/236454259-95d2eae2-af6c-4367-86cc-6eac8e3ae375.png">

- QubePay’s main features like escrow systems, smart contracts, link-based…etc. (Like below)
<img width="1258" alt="Screen Shot 2023-05-05 at 21 11 24" src="https://user-images.githubusercontent.com/54393289/236454530-daace09b-fec9-4cf3-adce-4b1acdc47274.png">

- How users will be benefited in short (Freelancers, Companies, DAO holders, NFT promoters…etc.)

- [x] Ask @Badhan978 about what to fix
- [x] Tell @Kunal-Khatri-1 about what to fix
- [x] @Kunal-Khatri-1 write code according to it

## Linked issues
#xx

## Additional context

<img width="1191" alt="Screen Shot 2023-05-02 at 20 33 30" src="https://user-images.githubusercontent.com/54393289/235654914-a233d67a-6480-44c9-9ad4-94a9e1d42804.png">

<img width="565" alt="Screen Shot 2023-05-05 at 20 56 35" src="https://user-images.githubusercontent.com/54393289/236451769-3e294fe0-ef15-42e0-9543-e1e0c6ec3398.png">

**Comment by shungo0222** [comment]
- [ ] @Kunal-Khatri-1 implement responsive design
