### ISSUE TITLE
Rerecord the demo video

### ISSUE THREAD

**Issue by shungo0222** [Succery-dev/escrow#55]
## About feature 

- [x] @shungo0222 Fix the code for video recording temporarily
- [x] @shungo0222 @Badhan978 Record the video
- [x] @shungo0222 Change it with the new video on HP

| Person | Sentence |
| --- | --- |
| Shungo | I checked your Twitter and wanted to ask if you're currently looking for writing work? |
| Badhan | Yes, I am! |
| Shungo | Great! I'd like you to write an introductory article about QubePay. Please check the terms below and let me know if they work for you! And if the terms work, please share your wallet address.<br><br>Deadline: 2 weeks from now (5/25)<br><br>Payment: 15,000 USDC<br><br>Content: An introductory article about QubePay, to be published on Medium, and at least 3,000 words long. |
| Badhan | I've checked the terms and I agree to them!<br>And this is my wallet address. 0x9d53101902859E9a3Ea0a48de3976A2A3326c422 |
| Shungo | [URL Link for contract detail] |
| Shungo | Thank you! Please review this link and if everything looks good, kindly sign it! |

**Create Contract**
| Section | Content |
| --- | --- |
| Title | An introductory article about QubePay |
| Detail | An introductory article about QubePay, to be published on Medium, and at least 3,000 words long. |
| Deadline | 2023, 5/25 JPT |
| Reward(USDC) | 15,000 |
| Lancer's wallet address | 0x9d53101902859E9a3Ea0a48de3976A2A3326c422 |

## Linked issues
#xx
